{"name": "test_answer4", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4\n +  where 3 = inc(2)", "trace": "def test_answer4():\n>       assert inc(2) == 4\nE       assert 3 == 4\nE        +  where 3 = inc(2)\n\nscript\\test_demo1.py:27: AssertionError"}, "start": 1567828616251, "stop": 1567828616251, "uuid": "7eebf620-8525-42d4-89b5-772709e3d640", "historyId": "285f51eb18539fe12844f373d534d781", "testCaseId": "f999d9ec359f659e6ee742edfd257770", "fullName": "script.test_demo1#test_answer4", "labels": [{"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_demo1"}, {"name": "host", "value": "DESKTOP-ELQ6K57"}, {"name": "thread", "value": "21176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_demo1"}]}