{"name": "test_answer5", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4\n +  where 3 = inc(2)", "trace": "def test_answer5():\n>       assert inc(2) == 4\nE       assert 3 == 4\nE        +  where 3 = inc(2)\n\nscript\\test_demo1.py:31: AssertionError"}, "start": 1567828616271, "stop": 1567828616271, "uuid": "e66b4cb0-d09d-4dc2-8746-9685ab6c9c22", "historyId": "fce2943e509abc39696bb4caed50e2fb", "testCaseId": "64b7483100a1d2010e2d02d3206646c1", "fullName": "script.test_demo1#test_answer5", "labels": [{"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_demo1"}, {"name": "host", "value": "DESKTOP-ELQ6K57"}, {"name": "thread", "value": "21176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_demo1"}]}