{"name": "test_answer3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4\n +  where 3 = inc(2)", "trace": "def test_answer3():\n    \n>       assert inc(2) == 4\nE       assert 3 == 4\nE        +  where 3 = inc(2)\n\nscript\\test_demo1.py:23: AssertionError"}, "start": 1567828616237, "stop": 1567828616238, "uuid": "f25fd691-eeae-4de5-8dc7-3e5c4711a681", "historyId": "1f54823e80ff22baf481dfed72af2916", "testCaseId": "938ccde1f3c9a838f06cac9b7139daa5", "fullName": "script.test_demo1#test_answer3", "labels": [{"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_demo1"}, {"name": "host", "value": "DESKTOP-ELQ6K57"}, {"name": "thread", "value": "21176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_demo1"}]}