{"name": "test_answer1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4\n +  where 3 = inc(2)", "trace": "def test_answer1():\n    \n>       assert inc(2) == 4\nE       assert 3 == 4\nE        +  where 3 = inc(2)\n\nscript\\test_demo1.py:14: AssertionError"}, "start": 1567828616215, "stop": 1567828616215, "uuid": "d6e9cd7b-0ee5-4f8d-a170-045358e345dc", "historyId": "35efca6a08a17c48bba4dfd753426891", "testCaseId": "6a2a8821b00512dd4f303fd48995c114", "fullName": "script.test_demo1#test_answer1", "labels": [{"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_demo1"}, {"name": "host", "value": "DESKTOP-ELQ6K57"}, {"name": "thread", "value": "21176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_demo1"}]}