{"name": "test_answer2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4\n +  where 3 = inc(2)", "trace": "def test_answer2():\n>       assert inc(2) == 4\nE       assert 3 == 4\nE        +  where 3 = inc(2)\n\nscript\\test_demo1.py:18: AssertionError"}, "start": 1567828616223, "stop": 1567828616223, "uuid": "a03f31b2-ec1b-4b7d-a078-e5430803b2ff", "historyId": "9c3059983f2f9e1113e3444db2c0b992", "testCaseId": "81e5ad72091c58d75eed3ab74c92bdff", "fullName": "script.test_demo1#test_answer2", "labels": [{"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_demo1"}, {"name": "host", "value": "DESKTOP-ELQ6K57"}, {"name": "thread", "value": "21176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_demo1"}]}